import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@emotion/react': require.resolve('@emotion/react'),
    },
  },
  optimizeDeps: {
    exclude: [
      '@mui/joy',
      '@mui/joy/styles',
      '@mui/joy/CssBaseline',
      '@mui/joy/Box',
      '@mui/joy/List',
      '@mui/joy/ListItem',
      '@mui/joy/ListItemButton',
      '@mui/joy/Textarea',
      '@mui/joy/Button',
      '@mui/joy/Stack',
      '@mui/joy/Avatar',
      '@mui/joy/Chip',
      '@mui/joy/ListDivider',
      '@mui/joy/Typography',
      '@mui/icons-material',
      'chunk-HYAN3SWL.js',
      'chunk-C5A6K6Z5.js',
      'chunk-2DXGFHJ5.js',
      'chunk-33EWZSQX.js',
      'chunk-RHYDBGYB.js',
      'chunk-SEVB6TOW.js',
      'chunk-H7BUZ26F.js',
      'chunk-ZTKQPEN7.js',
      'chunk-LKFTM7PT.js',
      'chunk-ADXRNG57.js',
      'chunk-GXNKABA3.js',
      'chunk-DYCOINE2.js',
      'chunk-ZITAL433.js',
      'chunk-NR3GMP46.js',
      'chunk-AAIAY2XZ.js',
      'chunk-WERA4PAH.js',
      'chunk-ZL7BEOIW.js',
      'chunk-UUDXQWQP.js',
      'chunk-7ZMQJBJR.js',
      'chunk-6HYZI5YJ.js',
      'chunk-YKZVSFYN.js',
      'chunk-7GYUVWAU.js',
      'chunk-6PXCFRNU.js',
      'chunk-CDWOCJU7.js',
      'chunk-3FE2FBPO.js',
      'chunk-ZNVTW3KB.js',
      'chunk-DU3WFBKJ.js',
      'chunk-2222VBFC.js',
      'chunk-LRQMNIKQ.js'
    ],
    include: [
      'prop-types',
      'react-is',
      '@mui/icons-material/DarkModeRounded',
      '@mui/icons-material/LightMode',
      '@mui/icons-material/PhotoCamera',
      '@mui/icons-material/AssignmentRounded',
      '@mui/icons-material/HomeRounded',
      '@mui/icons-material/ShoppingCartRounded',
      '@mui/icons-material/QuestionAnswerRounded',
      '@mui/icons-material/GroupRounded',
      '@mui/icons-material/SupportRounded',
      '@mui/icons-material/SettingsRounded',
      '@mui/icons-material/Storefront',
      '@mui/icons-material/AssignmentTurnedIn',
      '@mui/icons-material/KeyboardArrowDown'
    ]
  },
  server: {
    proxy: {
      '/api': 'http://localhost:3000',
    },
    hmr: {
      host: 'refactored-space-robot-97qrgx65675r2p46-3000.app.github.dev',
      port: 443,
      protocol: 'wss',
    },
  },
});
