name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install

    - name: Install Jest
      run: npm install jest

    - name: Run Unit Tests and Generate JSON Report
      run: npx jest --json --outputFile=jest-results.json

    - name: Format Jest JSON Report
      run: |
        node <<EOF
        const fs = require('fs');
        const rawData = JSON.parse(fs.readFileSync('jest-results.json'));
        const formattedData = {
          timestamp: new Date().toISOString(),
          total: rawData.numTotalTests,
          passed: rawData.numPassedTests,
          failed: rawData.numFailedTests,
          skipped: rawData.numPendingTests,
          suites: rawData.testResults.map(suite => ({
            name: suite.name,
            passed: suite.numPassingTests,
            failed: suite.numFailingTests,
            tests: suite.assertionResults.map(test => ({
              name: test.fullName,
              status: test.status,
              errorMessage: test.failureMessages.join('\n') || null
            }))
          }))
        };
        fs.writeFileSync('formatted-jest-results.json', JSON.stringify(formattedData, null, 2));
        EOF

    - name: Clone Testflow Repository
      uses: actions/checkout@v3
      with:
        repository: nicklasfangerfisk/Testflow
        token: ${{ secrets.GITHUB_TOKEN }}
        path: Testflow

    - name: Copy and Commit Jest Results
      run: |
        cp formatted-jest-results.json Testflow/data/jest-results.json
        cd Testflow
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add data/jest-results.json
        if ! git diff --cached --quiet; then
          git commit -m "Update Jest test results"
          git push
        fi
