name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install

    - name: Install Jest
      run: npm install jest

    - name: Run Unit Tests
      run: npm test
      continue-on-error: true

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    if: always()

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'

    - name: Install dependencies
      run: npm install

    - name: Post Test Results to Supabase
      run: |
        export SUPABASE_URL=${{ secrets.SUPABASE_URL }}
        export SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        node src/scripts/post-jest-results.js
